manifest:
  remotes:
    - name: Urie96
      url-base: https://github.com/Urie96
  projects:
    - name: zmk
      remote: Urie96
      revision: main
      import: app/west.yml
  self:
    path: config